### ISSUE TITLE
Can't save during global destruction

### ISSUE THREAD

**Issue by ungrim97** [PopeFelix/Mojo-UserAgent-Mockable#15]
Currently Mojo::UserAgent::Mockable performs its save when it is DESTROY'ed by going out of scope. During testing this is usually during Global Destruction. 

Sadly we can't rely on the order in which objects are DESTROY'ed, as such it is possible that the Mojo::Transaction objects stored in $self->{_transactions} may have all ready been demolished and thus leave it full of 'undef' elements. This causes save to die when attempting to serialize these values as they aren't Mojo::Transaction objects.

Is there any reason not to just save the state of $self->{_transactions} when the transaction finishes? and add a check in sub DESTROY to check if there are actual transactions available to save.

Happy to make a PR if this is something that seems sane

**Comment by PopeFelix** [comment]
Jeez, I need to check this more often. Yeah, go ahead and make a PR for it.

**Comment by PopeFelix** [comment]
Fixed in 1.56
