### ISSUE TITLE
No pass reports anymore

### ISSUE THREAD

**Issue by eserte** [PopeFelix/Mojo-UserAgent-Mockable#18]
See http://fast-matrix.cpantesters.org/?dist=Mojo-UserAgent-Mockable%201.53;reports=1#sl=7,1 --- at the time of writing the last successful test was on 2018-01-12.

Test log looks like this:
```
...
t/passthrough.t ..................... ok
t/passthrough_nonblocking.t ......... skipped: Museum API not responding properly
Bailout called.  Further testing stopped:  Museum API not responding properly
FAILED--Further testing stopped: Museum API not responding properly
Makefile:950: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
(make test exited with 512)
```

**Comment by PopeFelix** [comment]
Thanks for the info. I'll fiddle with it when I can.

**Comment by eserte** [comment]
I think 1.54 fixed this problem... but now there's another one (other issue).
