### ISSUE TITLE
Issues spurious warning in record mode if no directory specified

### ISSUE THREAD

**Issue by rmzg** [PopeFelix/Mojo-UserAgent-Mockable#3]
See title. If you use the mode 'record' and specify a local path, e.g. 'foo.out' then the END block will warn about a non-existent directory.

**Comment by PopeFelix** [comment]
Yep. I see that. Should be easy to fix; if you want to submit a patch, I'll look at it. (This is me trying to encourage more people to contribute to OSS)

**Comment by PopeFelix** [comment]
Fixed by H. Chienjo.
