### ISSUE TITLE
Normalize requests for comparison

### ISSUE THREAD

**Issue by jplindstrom** [PopeFelix/Mojo-UserAgent-Mockable#6]
In my test I have new ids generated on each test run, and therefore some requests will be structurally the same, but not literally the same. This is fine in this case.

At the moment I get this type of error:

```
URL path mismatch: got \"/thingy/38002/gizmo\", expected \"/thingy/37920/gizmo\"
```

I plan on making it possible for the application programmer to provide some kind of normalizing of the requests before they get turned over to the Compare object.

My current thought is an optional request_normalizer attribute on the Mojo::UserAgent::Mockable. This can be set to a subref which takes the two requests as arguments, and returns two cloned requests which are then passed to ->compare().

(Another way of doing this would be to provide a way to set the Compare object at initialization time, but that requires the Compare object to become part of the interface, it needs to be way more granular and expose a lot more as a public interface. Not sure if you want that since it's intentionally private right now.)

I plan to do this fairly soon. Please let me know how you think this aligns with the existing design.

**Comment by PopeFelix** [comment]
So something like this?

$ua = Mojo::UserAgent::Mockable->new(
      ....,
      request_normalizer => sub {
           my ($r1, $r2) = @_;
           ....
           return ($new_r1, $new_r2);
      }
);

On Fri, Jun 10, 2016 at 9:35 AM, Johan Lindstrom notifications@github.com
wrote:

> In my test I have new ids generated on each test run, and therefore some
> requests will be structurally the same, but not literally the same. This is
> fine in this case.
> 
> At the moment I get this type of error:
> 
> URL path mismatch: got \"/thingy/38002/gizmo\", expected \"/thingy/37920/gizmo\"
> 
> I plan on making it possible for the application programmer to provide
> some kind of normalizing of the requests before they get turned over to the
> Compare object.
> 
> My current thought is an optional request_normalizer attribute on the
> Mojo::UserAgent::Mockable. This can be set to a subref which takes the two
> requests as arguments, and returns two cloned requests which are then
> passed to ->compare().
> 
> (Another way of doing this would be to provide a way to set the Compare
> object at initialization time, but that requires the Compare object to
> become part of the interface, it needs to be way more granular and expose a
> lot more as a public interface. Not sure if you want that since it's
> intentionally private right now.)
> 
> I plan to do this fairly soon. Please let me know how you think this
> aligns with the existing design.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/PopeFelix/Mojo-UserAgent-Mockable/issues/6, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAJqGGiMYG155pwH5ZhVR8Uh-9obu6rgks5qKXYsgaJpZM4IzAtz
> .

## 

Kit Peters, W0KEH
GPG public key fingerpint: 1A12 04B6 0C80 306A B292  14FD 2C7A 1037 F666
46A7
Hello to any and all NSA, DEA, or other government or non-government agents
reading this email.  Tell me about your life; I'll tell you about mine.

**Comment by jplindstrom** [comment]
Yes.

Actually, it just struck me that since the whole point of this subref is to modify the requests, the calling code should clone the objects before passing them in.

But otherwise, exactly like that.

**Comment by PopeFelix** [comment]
I like it. Much more elegant than my solution of adding the
"ignore_headers" and "ignore_body" options. :)

On Fri, Jun 10, 2016 at 9:57 AM, Johan Lindstrom notifications@github.com
wrote:

> Yes.
> 
> Actually, it just struck me that since the whole point of this subref is
> to modify the requests, the calling code should clone the objects before
> passing them in.
> 
> But otherwise, exactly like that.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/PopeFelix/Mojo-UserAgent-Mockable/issues/6#issuecomment-225205480,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAJqGBGELxqc0NvjAytByAXJa7n55XzRks5qKXs_gaJpZM4IzAtz
> .

## 

Kit Peters, W0KEH
GPG public key fingerpint: 1A12 04B6 0C80 306A B292  14FD 2C7A 1037 F666
46A7
Hello to any and all NSA, DEA, or other government or non-government agents
reading this email.  Tell me about your life; I'll tell you about mine.

**Comment by jplindstrom** [comment]
Well, that's more usable for the common case, so this is just the high-effort way to make any case work.

I've got it working and documented, will write some tests on Monday and submit a PR.

**Comment by PopeFelix** [comment]
Excellent. I look forward to it. Probably won't review until later in the
week, as I'm traveling Monday.

On Fri, Jun 10, 2016 at 11:46 AM, Johan Lindstrom notifications@github.com
wrote:

> Well, that's more usable for the common case, so this is just the
> high-effort way to make any case work.
> 
> I've got it working and documented, will write some tests on Monday and
> submit a PR.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/PopeFelix/Mojo-UserAgent-Mockable/issues/6#issuecomment-225234675,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAJqGOVHRa_2aC0oqi4qkNIvqw8BD40Sks5qKZTKgaJpZM4IzAtz
> .

## 

Kit Peters, W0KEH
GPG public key fingerpint: 1A12 04B6 0C80 306A B292  14FD 2C7A 1037 F666
46A7
Hello to any and all NSA, DEA, or other government or non-government agents
reading this email.  Tell me about your life; I'll tell you about mine.
